POC: Use AWS S3 buckets
spacetelescope/acs-notebook pull request #22
Opened 2019-03-28 18:49 UTC by pllim

This is part of the work for https://jira.stsci.edu/browse/JUSI-8 by DATB.

Blocked by:

* https://jira.stsci.edu/browse/ASB-1593
* spacetelescope/crds#571

cc @stscicrawford

2019-03-29 14:57 UTC, nmiles2718 commented
Too much unnecessary cruft here. All that needs to be done is for the user to execute `Observations.enable_cloud_dataset()` in a cell proceeding the call to download found observations. No need for all the intermediate steps.

2019-03-29 16:42 UTC, nmiles2718 requested changes
Remove all steps that involve converting the `URI`s to `S3` URI`s and instead insert cell at the very beginning with `Observations.enable_cloud_dataset()`.  (See initial comment)

2019-03-29 20:23 UTC, pllim commented
@nmiles2718 , thank you very much for the review, which definitely cleaned things up. I think I have addressed your comment.

2024-12-16 20:06 UTC, sosey commented
closing - all notebooks are now maintained in the hst_notebooks repository

2024-12-16 20:06 UTC, closed without merging